"""added dialog relationship

Revision ID: 038f0adbf230
Revises: 00f2f997d591
Create Date: 2023-04-27 12:36:16.192614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038f0adbf230'
down_revision = '00f2f997d591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id')))
    op.create_foreign_key('fk_dialog_user', 'dialog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dialog_user', 'dialog', type_='foreignkey')
    op.drop_column('dialog', 'user_id')
    # ### end Alembic commands ###
