"""added is_active column to conversation

Revision ID: 7b8bf114d05d
Revises: afc751bffe2b
Create Date: 2023-05-07 19:01:16.011371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8bf114d05d'
down_revision = 'afc751bffe2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
